# Generated by Django 4.0.1 on 2022-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=None, verbose_name='Дата создания')),
                ('date_expiry', models.DateTimeField(default=None, verbose_name='Дата действия ссылки')),
                ('url', models.CharField(default=None, max_length=255, verbose_name='Ссылка')),
                ('short_id', models.CharField(default=None, max_length=25, unique=True, verbose_name='Ссылка ид')),
                ('short_url', models.CharField(default=None, max_length=255, unique=True, verbose_name='Сокращенная ссылка')),
                ('description', models.TextField(default=None, verbose_name='Описание')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архивная?')),
            ],
        ),
    ]
