# Generated by Django 4.0.1 on 2022-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinks',
            name='date_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата действия ссылки'),
        ),
    ]
